# Generated by Django 5.0 on 2025-08-29 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField(help_text='Código do Produto', max_length=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MinLengthValidator(1)], verbose_name='Código')),
                ('nome', models.CharField(help_text='Nome do item', max_length=10, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Nome')),
                ('valor', models.FloatField(help_text='Valor do item', max_length=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Valor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
