# Generated by Django 5.0 on 2025-08-29 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='cod',
            field=models.IntegerField(help_text='Código do Produto', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MinLengthValidator(1)], verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(help_text='Nome do item', max_length=10, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(4)], verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valor',
            field=models.FloatField(help_text='Valor do item', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(4)], verbose_name='Valor'),
        ),
    ]
