# Generated by Django 5.0 on 2025-08-29 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_produto_cod_alter_produto_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='cod',
            field=models.CharField(help_text='Código do Produto', max_length=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MinLengthValidator(1)], verbose_name='Código'),
        ),
    ]
