# Generated by Django 5.0 on 2025-08-29 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_produto_cod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='cod',
            field=models.CharField(help_text='Código do Produto', max_length=4, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(help_text='Nome do item', max_length=10, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valor',
            field=models.FloatField(help_text='Valor do item', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Valor'),
        ),
    ]
